### ISSUE TITLE
Change Project Name

### ISSUE THREAD

**Issue by clintonb** [ColemanGariety/witch#1]
I'm not sure if you were going for humor; but, the name "bitch" is not very good. Consider changing to a name that perhaps describes what this project does, such as "osx-notifier".

**Comment by ColemanGariety** [comment]
Added to v5 milestone. thx

**Comment by cp** [comment]
@clintonb I went ahead and created a non-vulgar fork, if you're into that kind of stuff. https://github.com/ColbyAley/Teller

**Comment by dpsk** [comment]
Aaron Paul approve this project name, BITCH
:)

**Comment by ColemanGariety** [comment]
Yeah I think I saw an interview once where Aaron said his favorite part of the show was coming up with clever solutions to automated testing. idk

**Comment by mdespuits** [comment]
:+1: Very useful tool, but I don't think many users would want to add this. Might not be offensive to you, but it is to some people

**Comment by dch** [comment]
+1 -- would you consider removing the gem, or at least renaming it? Will Future You always think this is cool? As an employer I'd certainly not be hiring you. Food for thought.

**Comment by akonwi** [comment]
I suggest "Yeller." It's a bit more aggressive than "Teller" and more like the current name. Plus it goes well with the main method of the module

**Comment by ColemanGariety** [comment]
@dch I understand your argument, and that's why future me will get a notification when v5 is due.

**Comment by reinh** [comment]
So you'll consider changing the name in 15 years? Maybe you'll have grown the fuck up by then.

As someone with friends and loved ones who have been hurt by sexist and discriminatory behavior exactly like this, fuck you very, very much.

**Comment by dch** [comment]
@reinh this thread's been civil, change doesn't come through being offensive.

**Comment by reinh** [comment]
@dch Really don't need you to police my tone right now. Nothing about this project deserves civility _at all_.

**Comment by dpsk** [comment]
@reinh if you find name offensive, just don't use this gem, easy as that. @ColbyAley even created "civil" version of this gem.
Drama thread.

**Comment by reinh** [comment]
@dpsk It is absolutely not enough to "just don't use the gem". Calling this a "drama thread" is a blatant attempt to marginalize my and others' voices.

**Comment by dpsk** [comment]
Why so? Author of this gem doesn't have any obligations to you. He is just open-sourced his own work.

**Comment by reinh** [comment]
@dpsk Are you really that willfully ignorant about the nature of community and shared spaces? We all have obligations to treat each other with the respect each person is deserved, and not to cause unnecessary harm. I bet you don't use this argument when other people discriminate against you.

**Comment by postmodern** [comment]
Could you explain why you named this gem bitch? I don't get it.

**Comment by drbrain** [comment]
Hello.

As a steward of the rubygems.org namespace, if someone were to [submit this name as offensive](http://help.rubygems.org) I would have a difficult time deciding in favor of keeping this name.

Based on the name and the [contents of the README](https://github.com/JacksonGariety/bitch/blob/master/README.md) it seems to me that a reasonable person would think this name and project were meant to be objectionable. I'm not exactly sure how all the slang in the examples is meant to be used, but it certainly doesn't seem positive.

I hope you will come to understand why other people are also complaining about this gem name in this issue, and why they find it objectionable.

**Comment by mdespuits** [comment]
@reinh Just because this project does not deserve civility (to you) doesn't mean you should be uncivil. Don't you become uncivil when you are uncivil to someone you view as uncivil? Just saying.

@dpsk Yes, we can avoid using it as I will until the name is changed. But it is a useful tool and there may not be another gem like it that is useful. (There is in this case, but that is not the point.

@JacksonGariety Yes, you may not find it offensive, but when submitting something to the world, do you really want something vulgar to reflect your work? I don't think the name you have given this gem is proper but in **very** few contexts, if any in this day and age. Besides, unless I read the README, I won't know what it does. It's not a meaningful name until it is explained, which makes it a meaningless name to someone searching for something like it.

**Comment by ColemanGariety** [comment]
Project re-named to kvetch.

The world is not black and white I suppose.

**Comment by cp** [comment]
Ooh much better.

**Comment by mdespuits** [comment]
@JacksonGariety Awesome! I like it.
