### ISSUE TITLE
Crushing

### ISSUE THREAD

**Issue by puzanov** [ColemanGariety/witch#4]
1 gem 'bitch'
  2 Bitch.yell("yo homie there's a problem")  

ESC[?47lESC8140:osxnotifications adminadmin$ ruby test.rb 
/Users/adminadmin/.rvm/gems/ruby-1.9.3-p448/gems/terminal-notifier-1.5.1/bin/terminal-notifier:13: [BUG] Segmentation fault
ruby 1.9.3p448 (2013-06-27 revision 41675) [x86_64-darwin10.8.0]

-- Control frame information -----------------------------------------------
c:0010 p:---- s:0033 b:0033 l:000032 d:000032 CFUNC  :exec
c:0009 p:0152 s:0027 b:0027 l:000026 d:000026 TOP    /Users/adminadmin/.rvm/gems/ruby-1.9.3-p448/gems/terminal-notifier-1.5.1/bin/terminal-notifier:13
c:0008 p:---- s:0025 b:0025 l:000024 d:000024 FINISH
c:0007 p:---- s:0023 b:0023 l:000022 d:000022 CFUNC  :load
c:0006 p:0167 s:0019 b:0019 l:0004a8 d:002118 EVAL   /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/bin/terminal-notifier:23
c:0005 p:---- s:0015 b:0015 l:000014 d:000014 FINISH
c:0004 p:---- s:0013 b:0013 l:000012 d:000012 CFUNC  :eval
c:0003 p:0101 s:0007 b:0007 l:0004a8 d:002340 EVAL   /Users/adminadmin/.rvm/gems/ruby-1.9.3-p448/bin/ruby_noexec_wrapper:14
c:0002 p:---- s:0004 b:0004 l:000003 d:000003 FINISH
c:0001 p:0000 s:0002 b:0002 l:0004a8 d:0004a8 TOP   

-- Ruby level backtrace information ----------------------------------------
/Users/adminadmin/.rvm/gems/ruby-1.9.3-p448/bin/ruby_noexec_wrapper:14:in `<main>'
/Users/adminadmin/.rvm/gems/ruby-1.9.3-p448/bin/ruby_noexec_wrapper:14:in`eval'
/Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/bin/terminal-notifier:23:in `<main>'
/Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/bin/terminal-notifier:23:in`load'
/Users/adminadmin/.rvm/gems/ruby-1.9.3-p448/gems/terminal-notifier-1.5.1/bin/terminal-notifier:13:in `<top (required)>'
/Users/adminadmin/.rvm/gems/ruby-1.9.3-p448/gems/terminal-notifier-1.5.1/bin/terminal-notifier:13:in`exec'

-- C level backtrace information -------------------------------------------

   See Crash Report log file under ~/Library/Logs/CrashReporter or
   /Library/Logs/CrashReporter, for the more detail of.

-- Other runtime information -----------------------------------------------
- Loaded script: /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/bin/terminal-notifier
- Loaded features:
  
  0 enumerator.so
  1 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/x86_64-darwin10.8.0/enc/encdb.bundle
  2 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/x86_64-darwin10.8.0/enc/trans/transdb.bundle
  3 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/x86_64-darwin10.8.0/rbconfig.rb
  4 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/compatibility.rb
  5 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/defaults.rb
  6 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/deprecate.rb
  7 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/errors.rb
  8 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/version.rb
  9 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/requirement.rb
  10 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/platform.rb
  11 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb
  12 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/exceptions.rb
  13 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_gem.rb
  14 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb
  15 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems.rb
  16 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/path_support.rb
  17 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb
  18 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/syntax_error.rb
  19 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/x86_64-darwin10.8.0/psych.bundle
  20 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/x86_64-darwin10.8.0/stringio.bundle
  21 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/nodes/node.rb
  22 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/nodes/stream.rb
  23 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/nodes/document.rb
  24 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/nodes/sequence.rb
  25 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/nodes/scalar.rb
  26 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/nodes/mapping.rb
  27 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/nodes/alias.rb
  28 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/nodes.rb
  29 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/streaming.rb
  30 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/visitors/visitor.rb
  31 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/x86_64-darwin10.8.0/strscan.bundle
  32 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/scalar_scanner.rb
  33 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/visitors/to_ruby.rb
  34 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/visitors/emitter.rb
  35 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/visitors/yaml_tree.rb
  36 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/json/ruby_events.rb
  37 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/visitors/json_tree.rb
  38 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/visitors/depth_first.rb
  39 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/visitors.rb
  40 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/handler.rb
  41 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/tree_builder.rb
  42 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/parser.rb
  43 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/omap.rb
  44 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/set.rb
  45 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/coder.rb
  46 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/core_ext.rb
  47 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/x86_64-darwin10.8.0/date_core.bundle
  48 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/date/format.rb
  49 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/date.rb
  50 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/deprecated.rb
  51 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/stream.rb
  52 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/json/yaml_events.rb
  53 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/json/tree_builder.rb
  54 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/json/stream.rb
  55 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych/handlers/document_stream.rb
  56 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych.rb
  57 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/yaml.rb
  58 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/x86_64-darwin10.8.0/etc.bundle
  59 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/fileutils.rb
  60 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/x86_64-darwin10.8.0/pathname.bundle
  61 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/pathname.rb
  62 /Users/adminadmin/.rvm/gems/ruby-1.9.3-p448/gems/bundler-1.3.5/lib/bundler/gem_path_manipulation.rb
  63 /Users/adminadmin/.rvm/gems/ruby-1.9.3-p448/gems/bundler-1.3.5/lib/bundler/gem_helpers.rb
  64 /Users/adminadmin/.rvm/gems/ruby-1.9.3-p448/gems/bundler-1.3.5/lib/bundler/match_platform.rb
  65 /Users/adminadmin/.rvm/gems/ruby-1.9.3-p448/gems/bundler-1.3.5/lib/bundler/rubygems_ext.rb
  66 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/user_interaction.rb
  67 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/config_file.rb
  68 /Users/adminadmin/.rvm/gems/ruby-1.9.3-p448/gems/bundler-1.3.5/lib/bundler/rubygems_integration.rb
  69 /Users/adminadmin/.rvm/gems/ruby-1.9.3-p448/gems/bundler-1.3.5/lib/bundler/version.rb
  70 /Users/adminadmin/.rvm/gems/ruby-1.9.3-p448/gems/bundler-1.3.5/lib/bundler.rb
  71 /Users/adminadmin/.rvm/gems/ruby-1.9.3-p448/gems/bundler-unload-1.0.2/lib/bundler-unload.rb
  72 /Users/adminadmin/.rvm/gems/ruby-1.9.3-p448/gems/rubygems-bundler-1.2.0/lib/rubygems-bundler/noexec.rb
  73 /Users/adminadmin/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/shellwords.rb
  74 /Users/adminadmin/.rvm/gems/ruby-1.9.3-p448/gems/terminal-notifier-1.5.1/lib/terminal-notifier.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

**Comment by ColemanGariety** [comment]
The bug report you pasted there seems to say there's a bug in your Ruby interpreter, sir.

Maybe try Ruby 2.0.0, report back here, and I'll re-open if the bug is still present.
